use std::collections::HashSet;

use serde_json::{json, Value};

use crate::state::Individual;
use crate::types::PhonemePalette;

/// Purely opaque codes ("belief_1".."belief_6") -- gated by real emergent
/// thresholds (religiosity/IQ/foxp2/tech), but the id itself carries no
/// content at all, not even a neutral descriptive word. This used to borrow
/// real comparative-religion category names as bucketing keys -- harmless
/// in isolation, but every display surface then had to individually
/// remember never to leak one
/// verbatim, and a slip anywhere (event log, report export, a stray debug
/// print) would present this population as having invented that exact
/// real-world religious concept, which it never earned: these are just
/// complexity tiers (see the thresholds below), with no theological content
/// behind the label at all. Making the id itself inert removes that whole
/// class of leak -- there is nothing left to leak. `client/src/utils/i18n.ts`
/// keeps a player-facing description per code (built only from these same
/// mechanical thresholds: required stage/IQ/foxp2/tech, never a religion
/// name) for display before a real label exists. `try_label_belief` below is
/// the only source of that real, player-facing label -- generated by the
/// population's own language, only once it can express one.
pub const BELIEF_ARCHETYPES: &[(&str, i32, f64, f64, &[&str])] = &[
    ("belief_1", 1, 0.0, 0.3, &[]),
    ("belief_2", 2, 0.3, 0.4, &[]),
    ("belief_3", 2, 0.4, 0.5, &[]),
    ("belief_4", 3, 0.5, 0.6, &["pottery"]),
    ("belief_5", 4, 0.6, 0.65, &["writing_system", "mathematics_basic"]),
    ("belief_6", 4, 0.7, 0.7, &["writing_system", "mathematics_basic"]),
];

/// A belief's public label only exists once the population's language has
/// actually reached the point of expressing "god"/"spirit" concepts
/// (proto-words, stage >= 3 -- see `language::CORE_CONCEPTS`). Before that,
/// the archetype is mechanically real (someone holds it, it can spread,
/// it can anchor a ritual) but literally has no name yet: nobody in the
/// population has the words to have coined one. Deterministic per
/// (belief_id, this simulation's phoneme palette) -- never a fixed
/// real-world religion name.
pub fn try_label_belief(belief_id: &str, population: &[Individual], palette: &PhonemePalette) -> Option<String> {
    let any_capable = population.iter().any(|i| i.alive && !i.is_dead && i.beliefs.contains(belief_id) && i.language.stage >= 3);
    if !any_capable {
        return None;
    }
    let raw = crate::language::generate_proto_word(belief_id, "belief", palette);
    if raw.is_empty() {
        return None;
    }
    let mut chars = raw.chars();
    chars.next().map(|first| first.to_uppercase().collect::<String>() + chars.as_str())
}

fn religiosity_of(p: &crate::types::Phenotype) -> f64 {
    // `> 0.0` here is a sentinel for "not yet computed" (compute_phenotype
    // always populates a real value in production, so this branch exists
    // only to give tests/fixtures using Phenotype::default() a sane fallback
    // rather than a hard 0.0 susceptibility). A genuinely-computed religiosity
    // landing on exactly 0.0 (belief_capacity == 0.0 and serotonin == 1.0 at
    // the same time) would fall through to this same fallback, but that's an
    // astronomically unlikely coincidence for continuous, randomly-seeded
    // genome values -- not worth an Option<f64> plumbed through every
    // Phenotype construction site to close.
    if p.religiosity > 0.0 {
        p.religiosity
    } else {
        (p.anxiety + p.curiosity) / 2.0
    }
}

pub fn try_form_belief(individual: &mut Individual, existing_beliefs: &mut HashSet<String>, discovered_techs: &HashSet<String>, world_state: &Value, sim_day: i32) -> Option<Value> {
    let p = &individual.phenotype;
    let religiosity = religiosity_of(p);
    let env_gain = 1.0
        + if world_state.get("recent_disaster").is_some() { 5.0 } else { 0.0 }
        + (1.0 - world_state.get("food_abundance").and_then(Value::as_f64).unwrap_or(0.5)).max(0.0) * 3.0;
    let reflection = individual.extra.get("_beliefReflection").and_then(Value::as_f64).unwrap_or(0.0) + env_gain;
    let threshold = 100.0 / (religiosity * p.fluid_intelligence).max(0.1);
    individual.extra.insert("_beliefReflection".to_string(), json!(reflection));
    if reflection < threshold {
        return None;
    }
    let lang_stage = individual.language.stage;
    let mut eligible: Vec<_> = BELIEF_ARCHETYPES
        .iter()
        .filter(|(name, lang_min, iq_min, foxp2_min, requires_tech)| {
            !existing_beliefs.contains(*name)
                && lang_stage >= *lang_min
                && p.fluid_intelligence >= *iq_min
                && individual.language.foxp2_expression >= *foxp2_min
                && !requires_tech.iter().any(|t| !discovered_techs.contains(*t))
        })
        .collect();
    if eligible.is_empty() {
        return None;
    }
    eligible.sort_by_key(|a| a.1);
    let (belief_id, stage, _, _, _) = eligible[0];
    existing_beliefs.insert((*belief_id).to_string());
    individual.beliefs.insert((*belief_id).to_string());
    individual.extra.insert("_beliefReflection".to_string(), json!(0));
    Some(json!({
        "type": "belief_formed",
        "belief_id": belief_id,
        "founder_id": individual.id,
        "day": sim_day,
        "importance": if *stage >= 3 { "high" } else { "medium" },
    }))
}

fn distance(ax: f64, ay: f64, bx: f64, by: f64) -> f64 {
    ((ax - bx).powi(2) + (ay - by).powi(2)).sqrt()
}

/// Belief only spreads to someone who is in a group with a believer, or
/// physically nearby one -- never to an arbitrary, unconnected individual.
pub fn update_belief_spread(population: &mut [Individual], existing_beliefs: &HashSet<String>, groups: &mut [Value], sim_day: i32) -> Vec<Value> {
    if existing_beliefs.is_empty() {
        return Vec::new();
    }
    let mut events = Vec::new();

    // Snapshot of positions/group_id/beliefs per belief, computed before any
    // mutation. Carrying each holder's own belief set here (instead of just
    // "has some belief") means the per-belief loop below can check it
    // directly instead of re-scanning the whole population for every holder
    // for every belief -- that re-scan was an O(beliefs * population^2) cost
    // that grew sharply once a group had more than a handful of believers.
    #[allow(clippy::type_complexity)]
    let holders: Vec<(String, f64, f64, Option<String>, HashSet<String>)> = population
        .iter()
        .filter(|i| !i.beliefs.is_empty())
        .map(|i| (i.id.clone(), i.x, i.y, i.group_id.clone(), i.beliefs.clone()))
        .collect();

    for belief in existing_beliefs {
        let groups_with_belief: HashSet<&str> = holders
            .iter()
            .filter(|(.., beliefs)| beliefs.contains(belief))
            .filter_map(|(_, _, _, gid, _)| gid.as_deref())
            .collect();
        let believer_positions: Vec<(f64, f64)> = holders
            .iter()
            .filter(|(.., beliefs)| beliefs.contains(belief))
            .map(|(_, x, y, ..)| (*x, *y))
            .collect();

        for individual in population.iter_mut() {
            if individual.beliefs.contains(belief) {
                continue;
            }
            let in_group = individual.group_id.as_deref().is_some_and(|gid| groups_with_belief.contains(gid));
            let nearby = !in_group && believer_positions.iter().any(|(bx, by)| distance(*bx, *by, individual.x, individual.y) < 2.0);
            if !in_group && !nearby {
                continue;
            }
            let susceptibility = religiosity_of(&individual.phenotype);
            let exposure = individual.extra.entry("_beliefExposure".to_string()).or_insert_with(|| json!({}));
            let current = exposure.get(belief).and_then(Value::as_i64).unwrap_or(0) + 1;
            if let Some(obj) = exposure.as_object_mut() {
                obj.insert(belief.clone(), json!(current));
            }
            let threshold = 80.0 / susceptibility.max(0.2);
            if (current as f64) < threshold {
                continue;
            }
            if let Some(obj) = individual.extra.get_mut("_beliefExposure").and_then(Value::as_object_mut) {
                obj.remove(belief);
            }
            individual.beliefs.insert(belief.clone());
            let group_id = individual.group_id.clone();
            if let Some(gid) = &group_id {
                if let Some(group) = groups.iter_mut().find(|g| g.get("id").and_then(Value::as_str) == Some(gid.as_str())) {
                    let tension = group.get("internal_tension").and_then(Value::as_f64).unwrap_or(0.5);
                    if let Some(obj) = group.as_object_mut() {
                        obj.insert("internal_tension".to_string(), json!((tension - 0.05).max(0.0)));
                    }
                }
            }
            events.push(json!({
                "type": "belief_spread",
                "belief_id": belief,
                "individual_id": individual.id,
                "group_id": group_id,
                "day": sim_day,
                "importance": "low"
            }));
        }
    }
    events
}

/// Fires at most once per group -- `group.has_ritual` gates re-emission once a
/// ritual has already emerged, mirroring the JS original (without this, the
/// same >60%-belief-share condition would re-fire the event every tick).
/// `members` is this group's own membership, already resolved by the caller
/// (see tick.rs) -- letting each call filter the *entire* population itself
/// was an O(groups * population) cost that got sharply worse as both grew.
pub fn check_ritual_emergence(group: &mut Value, members: &[&Individual], existing_beliefs: &HashSet<String>, sim_day: i32) -> Option<Value> {
    if group.get("has_ritual").is_some_and(|v| !v.is_null()) {
        return None;
    }
    if members.len() < 3 {
        return None;
    }
    // Sorted rather than iterated in HashSet's own (arbitrary, run-to-run
    // unstable) order: when multiple beliefs cross the 60% cohesion
    // threshold in the same tick, which one becomes "the" ritual must be a
    // deterministic function of which beliefs exist, not of this process's
    // particular hash-bucket layout -- otherwise identical population states
    // could pick a different winning ritual across separate runs/replays.
    let mut existing_beliefs: Vec<&String> = existing_beliefs.iter().collect();
    existing_beliefs.sort();
    for belief in existing_beliefs {
        let count = members.iter().filter(|m| m.beliefs.contains(belief)).count();
        if count as f64 / members.len() as f64 > 0.6 {
            if let Some(obj) = group.as_object_mut() {
                obj.insert("has_ritual".to_string(), json!(belief));
                obj.insert("ritual_cohesion".to_string(), json!(0.1));
            }
            return Some(json!({
                "type": "ritual_emerged",
                "group_id": group.get("id").cloned().unwrap_or(Value::Null),
                "belief": belief,
                "day": sim_day,
                "importance": "medium"
            }));
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{Language, Phenotype};

    fn make_ind(id: &str) -> Individual {
        Individual {
            id: id.to_string(),
            phenotype: Phenotype { religiosity: 0.7, fluid_intelligence: 0.6, anxiety: 0.5, curiosity: 0.5, ..Default::default() },
            language: Language { foxp2_expression: 0.5, ..Default::default() },
            ..Default::default()
        }
    }

    fn calm_world() -> Value {
        json!({ "food_abundance": 0.8 })
    }
    fn crisis_world() -> Value {
        json!({ "recent_disaster": true, "food_abundance": 0.1 })
    }

    // ── BELIEF_ARCHETYPES ────────────────────────────────────────────────

    #[test]
    fn six_archetypes_defined() {
        assert_eq!(BELIEF_ARCHETYPES.len(), 6);
    }

    #[test]
    fn belief_1_has_lowest_iq_min_and_stage() {
        let (_, stage, iq_min, ..) = BELIEF_ARCHETYPES.iter().find(|(n, ..)| *n == "belief_1").unwrap();
        assert_eq!(*iq_min, 0.0);
        assert_eq!(*stage, 1);
    }

    #[test]
    fn belief_4_requires_pottery_not_writing() {
        let (_, _, _, _, tech) = BELIEF_ARCHETYPES.iter().find(|(n, ..)| *n == "belief_4").unwrap();
        assert!(tech.contains(&"pottery"));
        assert!(!tech.contains(&"writing_system"));
    }

    #[test]
    fn belief_5_and_belief_6_require_writing_and_math() {
        let (_, _, _, _, b5) = BELIEF_ARCHETYPES.iter().find(|(n, ..)| *n == "belief_5").unwrap();
        assert!(b5.contains(&"writing_system") && b5.contains(&"mathematics_basic"));
        let (_, _, _, _, b6) = BELIEF_ARCHETYPES.iter().find(|(n, ..)| *n == "belief_6").unwrap();
        assert!(b6.contains(&"writing_system"));
    }

    #[test]
    fn archetype_stages_span_one_to_four() {
        let stages: Vec<i32> = BELIEF_ARCHETYPES.iter().map(|(_, s, ..)| *s).collect();
        assert_eq!(*stages.iter().min().unwrap(), 1);
        assert_eq!(*stages.iter().max().unwrap(), 4);
    }

    // ── tryFormBelief ────────────────────────────────────────────────────

    #[test]
    fn belief_does_not_form_before_threshold() {
        let mut ind = make_ind("i1");
        let result = try_form_belief(&mut ind, &mut HashSet::new(), &HashSet::new(), &calm_world(), 1);
        assert!(result.is_none());
    }

    #[test]
    fn belief_1_forms_once_threshold_is_exceeded() {
        let mut ind = Individual {
            id: "i1".to_string(),
            phenotype: Phenotype { religiosity: 0.9, fluid_intelligence: 0.8, anxiety: 0.5, curiosity: 0.5, ..Default::default() },
            // belief_1's lang_min is 1 -- see BELIEF_ARCHETYPES.
            language: Language { stage: 1, foxp2_expression: 0.4, ..Default::default() },
            extra: { let mut m = serde_json::Map::new(); m.insert("_beliefReflection".to_string(), json!(9999)); m },
            ..Default::default()
        };
        let result = try_form_belief(&mut ind, &mut HashSet::new(), &HashSet::new(), &calm_world(), 1);
        let ev = result.expect("should form a belief");
        assert_eq!(ev["belief_id"], "belief_1");
    }

    #[test]
    fn a_pre_linguistic_individual_can_never_form_any_belief_no_matter_how_high_their_other_stats_are() {
        // H-05 regression: try_form_belief used to ignore each archetype's
        // lang_min entirely, so a stage-0 (pre-linguistic, zero vocabulary)
        // individual with high IQ/foxp2/religiosity could be assigned an
        // advanced belief like belief_5 or belief_6 -- despite being
        // unable to know a single word (try_acquire_word_from_environment
        // itself requires stage >= 2).
        let mut ind = Individual {
            id: "i1".to_string(),
            phenotype: Phenotype { religiosity: 0.95, fluid_intelligence: 0.95, anxiety: 0.5, curiosity: 0.5, ..Default::default() },
            language: Language { stage: 0, foxp2_expression: 0.95, ..Default::default() },
            extra: { let mut m = serde_json::Map::new(); m.insert("_beliefReflection".to_string(), json!(999_999)); m },
            ..Default::default()
        };
        let mut discovered = HashSet::new();
        for t in ["writing_system", "mathematics_basic", "pottery"] {
            discovered.insert(t.to_string());
        }
        let result = try_form_belief(&mut ind, &mut HashSet::new(), &discovered, &calm_world(), 1);
        assert!(result.is_none(), "a stage-0 individual must not be able to form any belief, however high their other stats are");
    }

    #[test]
    fn disaster_speeds_up_accumulation() {
        let mut calm = make_ind("i1");
        let mut crisis = make_ind("i2");
        try_form_belief(&mut calm, &mut HashSet::new(), &HashSet::new(), &calm_world(), 1);
        try_form_belief(&mut crisis, &mut HashSet::new(), &HashSet::new(), &crisis_world(), 1);
        let calm_reflection = calm.extra["_beliefReflection"].as_f64().unwrap();
        let crisis_reflection = crisis.extra["_beliefReflection"].as_f64().unwrap();
        assert!(crisis_reflection > calm_reflection);
    }

    #[test]
    fn scarcity_speeds_up_accumulation() {
        let mut plenty = make_ind("i1");
        let mut scarce = make_ind("i2");
        try_form_belief(&mut plenty, &mut HashSet::new(), &HashSet::new(), &json!({ "food_abundance": 1.0 }), 1);
        try_form_belief(&mut scarce, &mut HashSet::new(), &HashSet::new(), &json!({ "food_abundance": 0.0 }), 1);
        assert!(scarce.extra["_beliefReflection"].as_f64().unwrap() > plenty.extra["_beliefReflection"].as_f64().unwrap());
    }

    #[test]
    fn already_held_belief_is_never_reassigned() {
        let mut ind = Individual {
            id: "i1".to_string(),
            phenotype: Phenotype { religiosity: 0.9, fluid_intelligence: 0.8, anxiety: 0.5, curiosity: 0.5, ..Default::default() },
            language: Language { foxp2_expression: 0.4, ..Default::default() },
            extra: { let mut m = serde_json::Map::new(); m.insert("_beliefReflection".to_string(), json!(9999)); m },
            ..Default::default()
        };
        let mut existing = HashSet::new();
        existing.insert("belief_1".to_string());
        let result = try_form_belief(&mut ind, &mut existing, &HashSet::new(), &calm_world(), 1);
        if let Some(ev) = result {
            assert_ne!(ev["belief_id"], "belief_1");
        }
    }

    #[test]
    fn belief_4_blocked_below_its_iq_threshold() {
        let mut ind = Individual {
            id: "i1".to_string(),
            phenotype: Phenotype { religiosity: 0.9, fluid_intelligence: 0.4, anxiety: 0.5, curiosity: 0.5, ..Default::default() },
            language: Language { foxp2_expression: 0.9, ..Default::default() },
            extra: { let mut m = serde_json::Map::new(); m.insert("_beliefReflection".to_string(), json!(9999)); m },
            ..Default::default()
        };
        let mut discovered = HashSet::new();
        discovered.insert("pottery".to_string());
        let mut existing = HashSet::new();
        for b in ["belief_1", "belief_2", "belief_3"] {
            existing.insert(b.to_string());
        }
        let result = try_form_belief(&mut ind, &mut existing, &discovered, &calm_world(), 1);
        if let Some(ev) = result {
            let id = ev["belief_id"].as_str().unwrap();
            assert!(!["belief_4", "belief_5", "belief_6"].contains(&id));
        }
    }

    #[test]
    fn accumulation_resets_after_crossing_threshold() {
        let mut ind = Individual {
            id: "i1".to_string(),
            phenotype: Phenotype { religiosity: 0.9, fluid_intelligence: 0.8, anxiety: 0.5, curiosity: 0.5, ..Default::default() },
            language: Language { stage: 1, foxp2_expression: 0.4, ..Default::default() },
            extra: { let mut m = serde_json::Map::new(); m.insert("_beliefReflection".to_string(), json!(9999)); m },
            ..Default::default()
        };
        try_form_belief(&mut ind, &mut HashSet::new(), &HashSet::new(), &calm_world(), 1);
        assert_eq!(ind.extra["_beliefReflection"], json!(0));
    }

    #[test]
    fn try_form_belief_never_touches_phenotype_fields() {
        let mut ind = Individual {
            id: "i1".to_string(),
            phenotype: Phenotype { religiosity: 0.9, fluid_intelligence: 0.8, anxiety: 0.5, curiosity: 0.5, ..Default::default() },
            language: Language { stage: 1, foxp2_expression: 0.9, ..Default::default() },
            extra: { let mut m = serde_json::Map::new(); m.insert("_beliefReflection".to_string(), json!(9999)); m },
            ..Default::default()
        };
        let before = ind.phenotype.clone();
        try_form_belief(&mut ind, &mut HashSet::new(), &HashSet::new(), &crisis_world(), 1);
        assert_eq!(ind.phenotype, before);
    }

    // ── updateBeliefSpread ───────────────────────────────────────────────

    #[test]
    fn same_group_neighbor_of_a_believer_can_receive_the_belief() {
        let mut believer = make_ind("b1");
        believer.group_id = Some("g1".to_string());
        believer.beliefs.insert("belief_1".to_string());
        let mut receptive = Individual {
            id: "r1".to_string(),
            group_id: Some("g1".to_string()),
            phenotype: Phenotype { religiosity: 0.9, anxiety: 0.5, curiosity: 0.5, fluid_intelligence: 0.5, ..Default::default() },
            extra: { let mut m = serde_json::Map::new(); m.insert("_beliefExposure".to_string(), json!({ "belief_1": 10000 })); m },
            ..Default::default()
        };
        let mut existing = HashSet::new();
        existing.insert("belief_1".to_string());
        let mut pop = vec![believer, std::mem::take(&mut receptive)];
        update_belief_spread(&mut pop, &existing, &mut [], 100);
        assert!(pop[1].beliefs.contains("belief_1"));
    }

    #[test]
    fn a_far_away_individual_in_a_different_group_never_receives_the_belief() {
        let mut believer = make_ind("b1");
        believer.group_id = Some("g1".to_string());
        believer.x = 0.0;
        believer.y = 0.0;
        believer.beliefs.insert("belief_1".to_string());
        let mut isolated = make_ind("r1");
        isolated.group_id = Some("g2".to_string());
        isolated.x = 10.0;
        isolated.y = 10.0;

        let mut existing = HashSet::new();
        existing.insert("belief_1".to_string());
        let mut pop = vec![believer, isolated];
        for day in 0..100 {
            update_belief_spread(&mut pop, &existing, &mut [], day);
        }
        assert!(!pop[1].beliefs.contains("belief_1"));
    }

    #[test]
    fn already_held_belief_produces_no_spread_events() {
        let mut holder = make_ind("h1");
        holder.group_id = Some("g1".to_string());
        holder.beliefs.insert("belief_1".to_string());
        let mut existing = HashSet::new();
        existing.insert("belief_1".to_string());
        let events = update_belief_spread(&mut [holder], &existing, &mut [], 1);
        assert!(events.is_empty());
    }

    #[test]
    fn empty_belief_set_returns_immediately() {
        let events = update_belief_spread(&mut [], &HashSet::new(), &mut [], 1);
        assert!(events.is_empty());
    }

    // ── checkRitualEmergence ─────────────────────────────────────────────

    #[test]
    fn ritual_emerges_once_over_sixty_percent_of_members_share_a_belief() {
        let mut members = [make_ind("i1"), make_ind("i2"), make_ind("i3"), make_ind("i4")];
        for m in members.iter_mut().take(3) {
            m.beliefs.insert("belief_1".to_string());
        }
        let mut group = json!({ "id": "g1", "member_ids": ["i1", "i2", "i3", "i4"], "has_ritual": Value::Null });
        let mut existing = HashSet::new();
        existing.insert("belief_1".to_string());
        let member_refs: Vec<&Individual> = members.iter().collect();
        let result = check_ritual_emergence(&mut group, &member_refs, &existing, 100);
        assert!(result.is_some());
        assert_eq!(result.unwrap()["type"], "ritual_emerged");
        assert_eq!(group["has_ritual"], "belief_1");
    }

    #[test]
    fn ritual_does_not_emerge_with_fewer_than_three_members() {
        let mut ind = make_ind("i1");
        ind.beliefs.insert("belief_1".to_string());
        let mut group = json!({ "id": "g1", "member_ids": ["i1"], "has_ritual": Value::Null });
        let mut existing = HashSet::new();
        existing.insert("belief_1".to_string());
        assert!(check_ritual_emergence(&mut group, &[&ind], &existing, 100).is_none());
    }

    #[test]
    fn when_two_beliefs_both_cross_the_threshold_the_winner_is_deterministic_not_hashset_order() {
        // Two different HashSets holding the exact same two belief ids,
        // built by inserting them in the opposite order -- HashSet's own
        // iteration order isn't guaranteed to depend on insertion order,
        // but this at least exercises both possible underlying bucket
        // layouts. Sorting before iterating (see check_ritual_emergence)
        // must make "belief_4" win both times, since it sorts before
        // "belief_5" -- not whichever the HashSet happens to yield first.
        let mut members = [make_ind("i1"), make_ind("i2"), make_ind("i3")];
        for m in members.iter_mut() {
            m.beliefs.insert("belief_5".to_string());
            m.beliefs.insert("belief_4".to_string());
        }
        let member_refs: Vec<&Individual> = members.iter().collect();

        let mut existing_a = HashSet::new();
        existing_a.insert("belief_4".to_string());
        existing_a.insert("belief_5".to_string());
        let mut group_a = json!({ "id": "ga", "member_ids": ["i1", "i2", "i3"], "has_ritual": Value::Null });
        let result_a = check_ritual_emergence(&mut group_a, &member_refs, &existing_a, 100).unwrap();

        let mut existing_b = HashSet::new();
        existing_b.insert("belief_5".to_string());
        existing_b.insert("belief_4".to_string());
        let mut group_b = json!({ "id": "gb", "member_ids": ["i1", "i2", "i3"], "has_ritual": Value::Null });
        let result_b = check_ritual_emergence(&mut group_b, &member_refs, &existing_b, 100).unwrap();

        assert_eq!(result_a["belief"], "belief_4");
        assert_eq!(result_b["belief"], "belief_4");
    }

    #[test]
    fn ritual_never_forms_twice_for_the_same_group() {
        let mut members = [make_ind("i1"), make_ind("i2"), make_ind("i3")];
        for m in members.iter_mut() {
            m.beliefs.insert("belief_1".to_string());
        }
        let mut group = json!({ "id": "g1", "member_ids": ["i1", "i2", "i3"], "has_ritual": "belief_1" });
        let mut existing = HashSet::new();
        existing.insert("belief_1".to_string());
        let member_refs: Vec<&Individual> = members.iter().collect();
        assert!(check_ritual_emergence(&mut group, &member_refs, &existing, 100).is_none());
    }

    // ── tryLabelBelief ──────────────────────────────────────────────────

    fn believer_at_stage(stage: i32, belief_id: &str) -> Individual {
        let mut ind = make_ind("i1");
        ind.alive = true;
        ind.language.stage = stage;
        ind.beliefs.insert(belief_id.to_string());
        ind
    }

    #[test]
    fn no_label_before_any_believer_reaches_proto_words() {
        let pop = vec![believer_at_stage(2, "belief_1")];
        assert!(try_label_belief("belief_1", &pop, &crate::language::full_palette()).is_none());
    }

    #[test]
    fn label_appears_once_a_believer_reaches_proto_words() {
        let pop = vec![believer_at_stage(3, "belief_1")];
        assert!(try_label_belief("belief_1", &pop, &crate::language::full_palette()).is_some());
    }

    #[test]
    fn a_believer_of_a_different_belief_does_not_unlock_this_labels() {
        let pop = vec![believer_at_stage(4, "belief_3")];
        assert!(try_label_belief("belief_1", &pop, &crate::language::full_palette()).is_none());
    }

    #[test]
    fn a_dead_capable_believer_does_not_unlock_a_label() {
        let mut ind = believer_at_stage(3, "belief_1");
        ind.alive = false;
        ind.is_dead = true;
        assert!(try_label_belief("belief_1", &[ind], &crate::language::full_palette()).is_none());
    }

    #[test]
    fn empty_palette_never_yields_a_label_even_when_capable() {
        let pop = vec![believer_at_stage(3, "belief_1")];
        assert!(try_label_belief("belief_1", &pop, &PhonemePalette::default()).is_none());
    }

    #[test]
    fn label_is_deterministic_for_the_same_belief_and_palette() {
        let pop = vec![believer_at_stage(3, "belief_1")];
        let palette = crate::language::full_palette();
        assert_eq!(try_label_belief("belief_1", &pop, &palette), try_label_belief("belief_1", &pop, &palette));
    }

    #[test]
    fn different_belief_ids_are_not_all_forced_to_the_same_label() {
        // Same weak-hash property as language::generate_proto_word itself
        // (see its own collision-tolerant test) -- two specific ids can
        // coincidentally collide, so this checks for variety across all six
        // archetypes rather than asserting any one fixed pair always differs.
        let palette = crate::language::full_palette();
        let labels: std::collections::HashSet<Option<String>> = BELIEF_ARCHETYPES
            .iter()
            .map(|(id, ..)| try_label_belief(id, &[believer_at_stage(3, id)], &palette))
            .collect();
        assert!(labels.len() > 1, "expected some variety across the six belief archetypes' labels");
    }
}
